### ISSUE TITLE
MinimalApiResultExtensions.ToMinimalApiResult is missing case for ResultStatus.NoContent

### ISSUE THREAD

**Issue by inghamc-csu** [ardalis/Result#191]
Tried to convert the Ardalis.Result return from my MediatR command to Microsoft.AspNetCore.Http.IResult using the ToMinimalApiResult() extension, and got a 500 from a thrown System.NotSupportedException when my Result value was Result.NoContent()

```
Assert.Fail(): Unhandled ResultStatus NoContent in MinimalApiResultExtensions.ToMinimalApiResult: System.NotSupportedException: Result NoContent conversion is not supported.
   at Ardalis.Result.AspNetCore.ResultExtensions.ToMinimalApiResult(IResult result) in /Users/inghamc/git/ardalis/inghamc.Result/src/Ardalis.Result.AspNetCore/MinimalApiResultExtensions.cs:line 48
   at Ardalis.Result.AspNetCore.ResultExtensions.ToMinimalApiResult(Result result) in /Users/inghamc/git/ardalis/inghamc.Result/src/Ardalis.Result.AspNetCore/MinimalApiResultExtensions.cs:line 32
```

I've added the missing case for `NoContent` and an xUnit test in a `tests/Ardalis.Result.AspNetCore.UnitTests/MinimalApiResultExtensionsCoverage.cs` that I'll include in a PR

**Comment by ardalis** [comment]
Sounds good thanks!

**Comment by inghamc** [comment]
Hi, any ETA on a release that would contain this fix?  Thanks!

**Comment by ardalis** [comment]
Probably next week; out of office this week

**Comment by inghamc** [comment]
Pretty please on the release request 🥺
